# Generated by Django 3.2.6 on 2021-08-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.DecimalField(decimal_places=15, max_digits=30)),
                ('y_axis', models.DecimalField(decimal_places=15, max_digits=30)),
                ('temperature', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
